/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    colors:{
      "black":"#000000",
      "green": "#C2FFC1",
      "dark-green": "#1F8829",
      "light-green" : "#ebf9eb",
      "white": "#FFFFFF",
      "dark-yellow": "#F3BB1C",
      "mid-yellow": "#EBDA9F",
      "mider-yellow": "rgba(243, 187, 28, 0.3)",
      "light-yellow": "#FEF9E9",
      "dark-red": "#C23631",
      "light-red": "#EBDBE1",
      "light-mid-red" : "#ecc1c0",
      "dark-brown": "#493808",
      "dark-skyblue": "#065BA1",
      "dark-blue": "#3A5AFE",
      "dark-midblue" :"#065ba1",
      "mid-light-gray": "#e2e2e2",
      "light-gray": "#73787B",
      "text-bg-gray": "#F3F3F3",
      "darkest-blue" :"#132847",
      "light-sky-blue" : "#E6EEF5",
      "lightest-gray" : "#E6EEF5",
      "dark-orange" : "#f26704",
      "light-orange" : "#FAE4A6",
      "top-gray": "f0f3f7",
      "light-brown" : "#a97607",
      "lightest-brown" : "#ecedf0",
      "light-mid-gray" : "#968d8d",
      "darker-blue" :"#1A5BA1",
      "dark-purple" : "#D36FF9",
      "dark-pink" : "#dd68a5",
      "blue":"#249ffb",
      "dark-peach" : "#ff7187",
      "light-purple": "#7b81df",
    },
    backgroundImage: {
      'purple-gradient': 'linear-gradient(to bottom, #B1B9F8 0%, #ADB7F9 100%)',
      'red-gradient': 'linear-gradient(to bottom, #F4A79D 0%, #F4A79D 100%)',
      'gray-gradient': "linear-gradient(to bottom, #1e293b, #4b5563)",
      "blue-gradient" : "bg-gradient-to-r from-slate-50 to-sky-200",
      
    },
   
  },
  plugins: [],
}